server:
  port: 8888

#应用名称
spring:
  application:
    name: eureka

eureka:
  instance:
    namespace: localhost
  client:
    #自己是否注册
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.namespace}:${server.port}/eureka
